### ISSUE TITLE
Getting error on 'mvn package'

### ISSUE THREAD

**Issue by far11ven** [extent-framework/extentreports-java#194]
As 5.0.0-Sanpshot is not yet available in mvn repository, I tried to package the v5.0x branch ,using mvn package
I'm getting following error:

D:\Workspace\Demo-Workspace\extentreports-java - Copy>mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] -----------------< com.aventstack:extentreports-java >------------------
[INFO] Building ExtentReports 5.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ extentreports-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 44 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:compile (default-compile) @ extentreports-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 118 source files to D:\Workspace\Demo-Workspace\extentreports-java - Copy\target\classes
[INFO]
[INFO] --- maven-resources-plugin:3.1.0:testResources (default-testResources) @ extentreports-java ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory D:\Workspace\Demo-Workspace\extentreports-java - Copy\src\test\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.6.1:testCompile (default-testCompile) @ extentreports-java ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 31 source files to D:\Workspace\Demo-Workspace\extentreports-java - Copy\target\test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/Workspace/Demo-Workspace/extentreports-java - Copy/src/test/java/com/aventstack/extentreports/reporter/OfflineReportTest.java:[10,36] cannot find symbol
  symbol:   class Base
  location: package com.aventstack.extentreports
**[ERROR] /D:/Workspace/Demo-Workspace/extentreports-java - Copy/src/test/java/com/aventstack/extentreports/reporter/OfflineReportTest.java:[12,40] cannot find symbol
  symbol: class Base**
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  14.654 s
[INFO] Finished at: 2020-06-24T12:06:42+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:testCompile (default-testCompile) on project extentreports-java: Compilation failure: Compilation failure:
[ERROR] /D:/Workspace/Demo-Workspace/extentreports-java - Copy/src/test/java/com/aventstack/extentreports/reporter/OfflineReportTest.java:[10,36] cannot find symbol
[ERROR]   symbol:   class Base
[ERROR]   location: package com.aventstack.extentreports
[ERROR] /D:/Workspace/Demo-Workspace/extentreports-java - Copy/src/test/java/com/aventstack/extentreports/reporter/OfflineReportTest.java:[12,40] cannot find symbol
[ERROR]   symbol: class Base
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by anshooarora** [comment]
Use the master branch, v5.0x should't be there anymore.  I will remove it.

You can use the SNAPSHOT release now,  I just pushed to nexus: https://oss.sonatype.org/content/repositories/snapshots/com/aventstack/extentreports/5.0.0-SNAPSHOT/

**Comment by far11ven** [comment]
@anshooarora @grasshopper7:

I'm using cucumber 5.5, with extent framework 5.0.0-Snapshot version from Sonatype
along with Grasshopper's adapter: extentreports-cucumber5-adapter v1.3.2

Still, I'm getting following error:


[INFO] Running com.kushal.testRunner.CucumberTestRunnerReporter
Jun 24, 2020 12:38:03 PM io.cucumber.testng.TestNGCucumberRunner <init>
WARNING: By default Cucumber is running in --non-strict mode.
This default will change to --strict and --non-strict will be removed.
You can use --strict or @CucumberOptions(strict = true) to suppress this warning
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 1.106 s <<< FAILURE! - in com.kushal.testRunner.CucumberTestRunnerReporter
_**[ERROR] setUpClass(com.kushal.testRunner.CucumberTestRunnerReporter)  Time elapsed: 0.756 s  <<< FAILURE!
io.cucumber.core.exception.CucumberException: java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ConfigurableReporter
Caused by: java.lang.NoClassDefFoundError: com/aventstack/extentreports/reporter/ConfigurableReporter
Caused by: java.lang.ClassNotFoundException: com.aventstack.extentreports.reporter.ConfigurableReporter**_

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   CucumberTestRunnerReporter>AbstractTestNGCucumberTests.setUpClass:22 » Cucumber
[INFO]
[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2

**Comment by anshooarora** [comment]
ExtentReports 5 - a huge update and is currently not supported by any adapters, I would suggest to wait until the release version or use 4.1.6.  For version 5 adapter, you shouldn't need to include extentreports dependency, the adapter would resolve it for you.

**Comment by far11ven** [comment]
Okay thanks for the Information.

**Comment by far11ven** [comment]
@anshooarora when I tried Extentreports v4.1.6 with cucumber 4.4.0 and extentreports-cucumber4-adapter v1.0.8

I'm getting the following error, it was working fine with Extentreports v4.0.9

[INFO] Running com.kushal.testRunner.CucumberTestRunnerReporter
Jun 25, 2020 10:51:41 AM cucumber.runtime.java.ObjectFactoryLoader loadSingleObjectFactory
WARNING: Use deprecated reflections to load ObjectFactory.
Feature: SuccessfulCheckoutFlow [Positive Senario]

  @demo1 @all @positive
  Scenario: TC_demo1 - Successful checkout with valid user   # src/test/resources/features/Demo/Demo.feature:5

0 Scenarios
0 Steps
0m0.422s

[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 2.542 s <<< FAILURE! - in com.kushal.testRunner.CucumberTestRunnerReporter
[ERROR] runScenario(com.kushal.testRunner.CucumberTestRunnerReporter)  Time elapsed: 0.413 s  <<< FAILURE!
java.lang.NoClassDefFoundError: com/aventstack/extentreports/ExtentReporter
Caused by: java.lang.ClassNotFoundException: com.aventstack.extentreports.ExtentReporter

[ERROR] reporterTeardown(com.kushal.testRunner.CucumberTestRunnerReporter)  Time elapsed: 0.414 s  <<< FAILURE!
java.lang.NoClassDefFoundError: Could not initialize class com.aventstack.extentreports.service.ExtentService$ExtentReportsLoader
        at com.kushal.testRunner.CucumberTestRunnerReporter.reporterTeardown(CucumberTestRunnerReporter.java:42)

[ERROR] tearDownClass(com.kushal.testRunner.CucumberTestRunnerReporter)  Time elapsed: 0.628 s  <<< FAILURE!
java.lang.NoClassDefFoundError: Could not initialize class com.aventstack.extentreports.service.ExtentService$ExtentReportsLoader

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   CucumberTestRunnerReporter.reporterTeardown:42 » NoClassDefFound Could not ini...
[ERROR]   CucumberTestRunnerReporter>AbstractTestNGCucumberTests.runScenario:22 » NoClassDefFound
[ERROR]   CucumberTestRunnerReporter>AbstractTestNGCucumberTests.tearDownClass:43 » NoClassDefFound
[INFO]
[ERROR] Tests run: 3, Failures: 3, Errors: 0, Skipped: 0

**Comment by grasshopper7** [comment]
@far11ven  Here is a first very 'rough' attempt at using extentreports 5 with cucumber 5. - https://github.com/grasshopper7/extentreports5-cucumber5-adapter. Adapter class has been modified appropriately but the ExtentService class is just hard coded to create the Spark report and needs to be refactored properly. Further details and findings can be found here - https://github.com/grasshopper7/extentreports5-cucumber5-adapter/blob/master/README.md.

@anshooarora I think the artifact id in this [wiki ](https://github.com/extent-framework/extentreports-java/wiki) should be extentreports-java instead of extentreports. Is spark the only available reporter from version 5 onwards?

**Comment by anshooarora** [comment]
@grasshopper7 Yes..  as it was getting difficult to maintain multiple formats.  In the future if there is a need for it, the other formats can be brought back. 

I have released initial support for Cucumber 4 adapter with only Spark and ExtentReports 5 SNAPSHOT here:  https://github.com/extent-framework/extentreports-cucumber4-adapter/tree/v1.2.x

Will also have a look at your code and send in a pull request if any updates are required.  Please note:  I have changed the Gherkin package in the [latest commit]() name back to `model` from `entity` to be aligned with version 4 and older plugins.  Apologies for this, but since v5 is very much in development, a lot of aspects may still change.

**Comment by anshooarora** [comment]
@grasshopper7 

Please review the pull request:  https://github.com/grasshopper7/extentreports5-cucumber5-adapter/pull/1

**Comment by anshooarora** [comment]
The screenshot arrangement is looking a little crowded, will look into this, but everything seems to be working.

![image](https://user-images.githubusercontent.com/4107384/85898943-17d33200-b7b2-11ea-8679-61f9c449f762.png)

![image](https://user-images.githubusercontent.com/4107384/85898969-2588b780-b7b2-11ea-8e3d-68194860a2ab.png)

The `Runs BEFORE scenarios..` and `Runs AFTER scenarios..` rows are not in their proper status, will also investigate this.

**Comment by grasshopper7** [comment]
@anshooarora Thanks for making changes to the adapter code. Have merged the PR.

I tried out the code and there seems to be a problem. So I tried with the adapter version 4 code and the result was the same. Have not had the time to determine the root cause. Will give it a try tomorrow.

I have created an issue which mentions more details. - https://github.com/extent-framework/extentreports-cucumber4-adapter/issues/60

**Comment by anshooarora** [comment]
@grasshopper7 Thanks,  I made the fix for scenario counts, however I am not sure how to tackle steps as the report will count every node as a step, including hooks.  ExtentReports requires a way to show the step without counting it - an exclusion criteria.
